# Variable for gcc flags
CFLAGS = -g -Wall --pedantic

# Default (First) Target
program: program.c
	gcc ${CFLAGS} program.c -o program

# Commonly used target for cleaning up targets
clean:
	rm program